### ISSUE TITLE
how to build it?

### ISSUE THREAD

**Issue by BestP2P** [coslyk/moonplayer#101]
is there any build guide?

**Comment by coslyk** [comment]
Please read the README.

**Comment by lowy** [comment]
Debian unstable
debianopt由于依赖问题无法安装 尝试源码安装反馈失败如下:
 lowy@debian  ~/moonplayer  mkdir buiid                  ✔  9261  13:36:21
 lowy@debian  ~/moonplayer  ls buiid                     ✔  9262  13:36:55
 lowy@debian  ~/moonplayer  cd buiid                     ✔  9263  13:37:03
 lowy@debian  ~/moonplayer/buiid  cmake ..               ✔  9264  13:37:09
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPV: /usr/include  
CMake Error at 3rdparty/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/lowy/moonplayer/3rdparty/danmaku2ass_cpp

  does not contain a CMakeLists.txt file.


-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.0")  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.72.0")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/home/lowy/moonplayer/buiid/CMakeFiles/CMakeOutput.log".
See also "/home/lowy/moonplayer/buiid/CMakeFiles/CMakeError.log".

**Comment by coslyk** [comment]
@lowy 你需要clone submodule：
```
git glone --recursive --branch v3.6 https://github.com/coslyk/moonplayer.git
```

**Comment by lowy** [comment]
ok
