### ISSUE TITLE
Dark theme for Classic UI

### ISSUE THREAD

**Issue by cybardev** [coslyk/moonplayer#103]
**Is your feature request related to a problem? Please describe.**
The Normal UI has "issues" with my DE plugins, themes, etc. setup. The Classic UI works flawlessly and I prefer how the bottom bar looks here. But I liked how the menus and everything in Normal UI could be set to Dark theme and would like the Dark theme to work on Classic UI too.

**Describe the solution you'd like**
I would like the Classic UI mode to have a Dark variant which could be toggled from the settings like in the Normal UI mode.

**Describe alternatives you've considered**
I have used the Normal UI, but I prefer the Classic one instead.

**Additional context**
It might look like this (edited in GIMP):

![image](https://user-images.githubusercontent.com/50134239/102014662-4bfed700-3d81-11eb-91fe-c26d8fd7ee94.png)

PS: The titlebar is my system titlebar, not the Normal UI titlebar.

**Comment by coslyk** [comment]
Thanks for your suggestion! I just add dark theme support in the latest commit.

Unfortunately, Qt does not provide API to enable dark theme in classic UI manually and it only reads settings from system, so you may need to set the system theme to the dark one. (Or maybe your system supports application-specific dark theme settings?)

**Comment by cybardev** [comment]
> Thanks for your suggestion! I just add dark theme support in the latest commit.

Thank you. Will check it out. 😊
> Unfortunately, Qt does not provide API to enable dark theme in classic UI manually and it only reads settings from system, so you may need to set the system theme to the dark one. (Or maybe your system supports application-specific dark theme settings?)

I'll have to see if Kvantum helps. I'll close the issue after I check it (or you can if you want to).

**Comment by cybardev** [comment]
@coslyk I'm sorry, I'm not sure what I have to do to trigger the dark theme in Classic UI. I use KvMojave (a dark theme) as my Kvantum theme. I have also tried another dark KvAntum theme but that doesn't change anything either.

Do I have to build from source, or is this AppImage enough? (I just tested the AppImage)

![image](https://user-images.githubusercontent.com/50134239/102119525-70cf7900-3e6b-11eb-85d5-30c3cd88d696.png)

**Comment by coslyk** [comment]
The dark theme in classic UI requires Qt 5.15 or later, but the Qt bundled in AppImage is 5.12. I will update it to the latest version later.

**Comment by cybardev** [comment]
Oh, ok. Thanks. I'll close it for now.

**Comment by cybardev** [comment]
> The dark theme in classic UI requires Qt 5.15 or later, but the Qt bundled in AppImage is 5.12. I will update it to the latest version later.

I've installed `moonplayer 3.7-1` from AUR and have `qt-5 base 5.15.2-2` installed. Classic UI still doesn't show an option for dark mode. Is there something else I need to do?

**Comment by coslyk** [comment]
You need to set the system theme to the dark mode.

**Comment by cybardev** [comment]
> You need to set the system theme to the dark mode.

Is there any Environment Variable that needs to be set? I use XFCE, and I use a dark GTK theme as well as a dark Qt theme via Kvantum and Qt settings.
