### ISSUE TITLE
作者大大是否考虑更换一下软件图标？

### ISSUE THREAD

**Issue by lowy** [coslyk/moonplayer#104]
原本的图标跟现代的整体风格有点不搭 之前openSUSE的源里那个图标就很不错 我删掉了周围一圈做成圆形 效果如下：
![2020-12-14_18-39](https://user-images.githubusercontent.com/6565177/102072867-6b5b3a00-3e3d-11eb-94fb-7ca71386364e.png)
希望能使用这个图标
![moonplayer001](https://user-images.githubusercontent.com/6565177/102073024-a3fb1380-3e3d-11eb-9a32-fd23c8c6cf13.png)

**Comment by coslyk** [comment]
感谢！不过感觉背景有点花，背景的图案去掉会不会好点？颜色的话，我感觉elementary的配色方案不错：https://elementary.io/docs/human-interface-guidelines#color
