### ISSUE TITLE
Archlinux KDE下播放会将音量调节到最大。

### ISSUE THREAD

**Issue by hzy199411** [coslyk/moonplayer#11]
Archlinux KDE下每次播放时会将自动音量调节到最大，请问这是什么问题？另外调节音量会改变系统的音量大小，这样很不好，会影响到其他程序，请修复一下。

**Comment by coslyk** [comment]
试试在~/.mplayer中，打开config（如没有则新建该文件），添加
softvol = "yes"
保存后重新播放试试。

**Comment by hzy199411** [comment]
这样可以，但是能把这个在程序中设为默认吗？另外moonplayer中的音量能保存吗？

**Comment by coslyk** [comment]
好的，下次更新我把softvol添加到设置里面
