### ISSUE TITLE
Feature Request: Auto prompt cursor ready for pasting when 'U' (open URL)

### ISSUE THREAD

**Issue by danrobi11** [coslyk/moonplayer#113]
When I use the shortcut 'U' to open a URL I cant paste the URL with ctrl+v because the cursor is not auto prompted. 

Therefore, I need to use my mouse to click to paste the URL.  Its annoying to have to use the mouse to paste the URL since I already use the keyboard shortcut to open the URL I shouldnt need to use the mouse to prompt the cursor in order to be able to paste the URL.

flatpak version 3.8

**Comment by coslyk** [comment]
Thanks for your suggestion! Fixed in https://github.com/coslyk/moonplayer/commit/e0219ca3ed0e8d133461e066a1774c21266a3832
