### ISSUE TITLE
[Feature Request] Enqueue Files in Playlist (without interrupting current playback)

### ISSUE THREAD

**Issue by MintMain21** [coslyk/moonplayer#115]
The Issue?
SMPLayer and Celluloid (both of which use MPV as a backend like MoonPlayer) allow me to enqueue files to the playlist without interrupting current playback. MoonPlayer allows me to add additional media to the playlist, but it always jumps to it upon loading, interrupting current playback.

A solution?
All I would really like is some kind of option/checkbox in the settings dialog to control whether playback is interrupted upon adding files/media to a playlist.

**Comment by coslyk** [comment]
Thanks for your suggestion.
