### ISSUE TITLE
error libopengl

### ISSUE THREAD

**Issue by lucasmz1** [coslyk/moonplayer#117]
missing libopengl in fedora 35
by the way wich version of ubuntu are you using to compile this app?

**Comment by coslyk** [comment]
Are you using the AppImage version? I compile it on Ubuntu 18.04 because it is the oldest version supported by Github Actions.

**Comment by lucasmz1** [comment]
yes I am using appimage. I suggest you made a better script to run it, a better apprun.

**Comment by lucasmz1** [comment]
can you make a appimage for armhf from your moonplayer?

**Comment by coslyk** [comment]
libopengl.0.so is excluded from the AppImage because it is hardware dependent (Check https://github.com/AppImage/pkg2appimage/blob/master/excludelist#L50).

Make sure you have install graphic driver properly.
