### ISSUE TITLE
[Feature Request] Predefined web video resolutions

### ISSUE THREAD

**Issue by dCo3lh0** [coslyk/moonplayer#119]
**Is your feature request related to a problem? Please describe.**
When i open youtube or other video sources (Odysee, rumble, flote, bitchute) with moonplayer i have to always select the video resolution and video format/codec option, if webm or mp4. There isnt a option to open on the go the video without having to select these first.

**Describe the solution you'd like**
Define a range of resolution that you want to open by default. The Max Res (my case 1080p, my monitor isnt 4k), the Min Res (480p) and 2 boxes one to select the better option by default, and another to open video anyways if the video source content isnt avalaible in the range you selected (example a 360p or 240p, or 2160p or 4k)

**Describe alternatives you've considered**
Nah, i didnt considered alternatives, i just considered having this box not show when opening a video, Youtubedl-gui, for example, for downloading, not playing videos have a default option, but for downloading, it selects the best option without you having to select it in the dropdown list.

**Additional context**
Nah, just excelent player, i really like it for basing itself in MPV, having its good hardware decoding integration, its my best video player for web content now.

**Comment by borisorlov21** [comment]
Thank you for a great player compared with others yours plays great
