### ISSUE TITLE
xp系统下显示不是win32程序 但win7下运行正常

### ISSUE THREAD

**Issue by ys0mh** [coslyk/moonplayer#12]
xp系统下显示不是win32程序 但win7下运行正常，这是什么原因呢？使用的是
moonplayer_v0.33.rar 这个包

**Comment by coslyk** [comment]
非常抱歉，最新版本已不再支持Win XP了，建议升级系统到Win7以上。

**Comment by ys0mh** [comment]
你好 能在网盘里同时放出支持xp的最后版本吗 家里老爷机实在跑不动win7

**Comment by coslyk** [comment]
抱歉我一个人没那么多精力去测试维护那么多系统。。。旧版本我没有存档而且早就不能用了，视频网站的解析算法变化很快的

**Comment by hzy199411** [comment]
刚刚用vs2010+qt4编译了一个兼容xp的最新版,你可以试试:
http://pan.baidu.com/s/1i3pOdEX 提取密码:cjsr

**Comment by coslyk** [comment]
感谢！
