### ISSUE TITLE
[BUG] Unable to run MoonPlayer AppImage on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [coslyk/moonplayer#120]
**Describe the bug**
Unable to run MoonPlayer v4.0 AppImage on Ubuntu 22.04 Wayland

**Error output**
![Screenshot from 2022-05-14 13-25-23](https://user-images.githubusercontent.com/46480489/168422109-d621bba3-5bad-408d-a31b-07abdf152a5a.png)

**Comment by coslyk** [comment]
Hello,

I have rebuilt the AppImage: https://github.com/coslyk/moonplayer/releases/tag/v4.0 can you try the new one?

**Comment by manikandancode** [comment]
Now working. Thanks
