### ISSUE TITLE
支持 mpv 后端

### ISSUE THREAD

**Issue by amitbha** [coslyk/moonplayer#13]
mplayer2貌似开发已停滞了，我在 ubuntu15.04 上使用时经常花屏
是否考虑支持 mpv 后端？

**Comment by coslyk** [comment]
把mplayer2换成mplayer试试
```
sudo apt-get remove mplayer2
sudo apt-get install mplayer
```

**Comment by amitbha** [comment]
可是 mplayer 和 mplayer2 都停止开发了，这是个问题

**Comment by coslyk** [comment]
mplayer官网上的最新编译是20150408，可能是ubuntu的仓库比较老旧吧，我的debian上的版本也是今年最新编译的

你的建议我也会考虑的。

**Comment by m13253** [comment]
> 是否考虑支持 mpv 后端？

如果是需要看B站，推荐 https://github.com/m13253/BiliDan

**Comment by Goshin** [comment]
> 是否考虑支持 mpv 后端？

可以试试这个 https://github.com/Goshin/Yatto
mpv 后端，依赖 flvcd 解析，支持 youku / tudou，分段视频合并播放。
支持土豆弹幕，还在完善之中。
