### ISSUE TITLE
Qt and exe

### ISSUE THREAD

**Issue by trimechee** [coslyk/moonplayer#131]
Hello, what is the difference between MoonPlayer_win_x64.exe and MoonPlayer_win_x64_qt5.exe please ? and which version is better for windows 10 os ? there will be version with qt6 please ?

**Comment by coslyk** [comment]
MoonPlayer_win_x64.exe is compiled with Qt6 and MoonPlayer_win_x64_qt5.exe is compiled with Qt5. The Qt5 version is just for compatibility with Win8.1 and lower and will be abandoned in the future.

**Comment by trimechee** [comment]
Awesome ! Thank you so much for this wonderful amazing player 🥇 💯
