### ISSUE TITLE
Audio only mode for local playback and for youtube streaming video

### ISSUE THREAD

**Issue by trimechee** [coslyk/moonplayer#138]
Hello, thank you again for this amazing wonderful media player !! 🥇 💯 

I have request please to make setting for youtube audio only to favor an exclusively audio stream (if available),  so we hope to have this feature in MoonPlayer because i often sleep and putting adress url of tv shows and documentaries and podcast in playlist of the media player and to save data and battery and power and to avoid the fan running and being noisy and waking me up and to prevent the screen not stay enabled at night, it will be great if MoonPlayer has an 'audio only' mode for streaming videos from youtube and even from other streaming platforms if available ! Thank you so much :) 

in the same way, I like to listen to TV shows.... I download them as MP4 from streaming sites (other sites different from youtube) but I just want to listen to the audio when I sleep so that my computer screen stays off and consumes less resources, can the marvelous MoonPlayer add an option or easy access button in the main interface to turn off the video with one click and thus only listen to the audio of the local donwloade video please ? in vlc player, there is an option to disable the video but we have to click several times to do that and it's not practical and fast, thank you very much !

**Comment by coslyk** [comment]
Added in v4.3.

**Comment by trimechee** [comment]
Fantastic !! Thank you so much Mr @coslyk ! 🥇
