### ISSUE TITLE
希望增加 Acfun 和土豆豆泡弹幕支持

### ISSUE THREAD

**Issue by m13253** [coslyk/moonplayer#14]
希望增加 Acfun 和土豆豆泡弹幕支持。

**Comment by coslyk** [comment]
嗯嗯，下个版本就加上！

**Comment by coslyk** [comment]
已经加上acfun了。

**Comment by lowy** [comment]
感谢作者大大的努力为我们linux用户提供了这么好的视频软件 不过越是好的东西就越希望能够更加完美 咳咳 那个图标是不是可以考虑换一下 之前openSUSE为这款软件打包所设计的黄月亮图标就挺漂亮的 
PS AB站的弹幕都有了 不知道C站... 阿啦 有点得陇望蜀 贪得无厌了 哈哈

**Comment by coslyk** [comment]
其实黄月亮图标是以前版本用的，我一个朋友帮我做的，不过好多人说不好看所以我就换了。。。每个人的审美都不同嘛，不过我倒是可以找学设计的朋友再帮忙再做一个图标呵呵。
