### ISSUE TITLE
ImportError: No module named flvcd_parser

### ISSUE THREAD

**Issue by 910JQK** [coslyk/moonplayer#15]
<pre>
./moonplayer 
Checking another instance...
Initialize settings...
Initialize API for Python...
Initialize language support...
Initialize player...
Initialize mplayer backend...
Initialize playlist...
Initialize webview...
ImportError: No module named flvcd_parser
</pre>
Distro: Arch Linux
Qt Version: 5.5.0
Moonplayer Version: b9dec4e

**Comment by coslyk** [comment]
make之后要
make install
然后直接终端执行moonplayer，
直接在编译目录下执行./moonplayer是不行的

**Comment by 910JQK** [comment]
SOLVED
