### ISSUE TITLE
ffmpeg放置位置

### ISSUE THREAD

**Issue by bohelinux** [coslyk/moonplayer#16]
按照作者提示，为了能够自动合并下载的视频，在Linux下需要把ffmpeg放在～/.moonplayer下。

现在我想让每个用户都可以使用这个功能，请问是否可以把ffmpeg放置在系统某个位置？
我试过放在/usr/share/moonplayer下，无法凑效，仍旧提示把ffmpeg放在～/.moonplayer下。

**Comment by coslyk** [comment]
谢谢你的建议！

**Comment by mikicomo** [comment]
支持一下作者，支持一下开源，follow！
