### ISSUE TITLE
输入框无法输入中文

### ISSUE THREAD

**Issue by kissthink** [coslyk/moonplayer#17]
之前的版本还可以，最新版本的编译后，无法正常输入中文，可以复制过去，但是无法输入

**Comment by coslyk** [comment]
请问你用的是什么输入法？

**Comment by kissthink** [comment]
fcitx

**Comment by coslyk** [comment]
你看看fcitx-frontend-qt5安装了没有？
抱歉最近特别忙，可能没法及时回复～

**Comment by bobbywinon** [comment]
我用xubuntu的ibus拼音也是不能在0.52版本下输入中文
