### ISSUE TITLE
fedora下FUZG源无法下载moonplayer

### ISSUE THREAD

**Issue by Dannnnniel-Zhang** [coslyk/moonplayer#21]
报错如下：
错误：nothing provides mencoder needed by moonplayer-0.49-1.gitbbf096e.fc23.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
应该怎么办啊……新手求问。系统是2016/03/15刚更新的。

**Comment by coslyk** [comment]
FZUG源不是我维护的，你去FZUG的Github页面反馈吧。

https://github.com/FZUG/repo

**Comment by 1dot75cm** [comment]
mencoder 出自 rpmfusion-free-updates-testing 源。 @Dannnnniel-Zhang 
```
$ dnf list | grep mencoder
mencoder.x86_64                       1.2.1-1.fc23              @rpmfusion-free-updates-testing
mencoder.i686                         1.1-33.20150505svn.fc22   rpmfusion-free 
```
