### ISSUE TITLE
0.59版，无法启动 No module named plugin_youku

### ISSUE THREAD

**Issue by XieQirong** [coslyk/moonplayer#23]
Linux Mint 64bit，通过添加PPA安装的moonplayer 0.59,无法启动，提示缺少优酷插件

> archxr@U410 ~ $ moonplayer 
Checking another instance...
Initialize settings...
Initialize API for Python...
Initialize language support...
Initialize player...
Initialize mplayer backend...
Initialize playlist...
Initialize webview...
Traceback (most recent call last):
  File "/usr/share/moonplayer/plugins/plugin_tudou.py", line 6, in <module>
    import plugin_youku
ImportError: No module named plugin_youku

**Comment by coslyk** [comment]
抱歉昨天更新疏忽了。。。刚刚把修复推送到ppa上了，你更新试试

**Comment by XieQirong** [comment]
OK了，辛苦了
