### ISSUE TITLE
在window7中无法启动该程序，提示计算机丢失python27.dll

### ISSUE THREAD

**Issue by Linux-pdz** [coslyk/moonplayer#25]
我将moonplayer_v0.62_windows.rar解压到D盘后，启动moonplayer.exe程序，却发现错误提示框，并告诉我，无法启动此程序，因为计算机丢失python27.dll。注：我使用的计算机平台为windows7旗舰版

**Comment by coslyk** [comment]
压缩包里面的说明有写，要安装python2.7
