### ISSUE TITLE
Could you maintain an official AUR 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [coslyk/moonplayer#29]
Hello,

I wonder if you can maintain an official AUR package for archlinux and arch-based distros users?
For now there was a contributor who built a moonplayer in AUR, but it haven't been updated almost 1 years.

Best regards

**Comment by levinit** [comment]
哈，我希望谁来维护一个archlinux的aur，目前aur的moonplayer是2015年的了。
https://aur.archlinux.org/packages/moonplayer

**Comment by coslyk** [comment]
抱歉，个人精力有限啊，我只维护ubuntu ppa，还是希望有人能继续帮忙维护aur的。。。

**Comment by levinit** [comment]
那位维护者已经更新了。
昨天下午才在aur中给了维护者提醒，没多久他就更新了。

**Comment by coslyk** [comment]
@levinit 太棒啦！谢谢那位兄弟！
