### ISSUE TITLE
似乎作为外部播放器有点问题？

### ISSUE THREAD

**Issue by yinflying** [coslyk/moonplayer#30]
安装好firefox插件后，右键“use moonplayer to open this page" ，moonplyer会提示是否下载，但是之后就无法播放了，”Network error...."

**Comment by yinflying** [comment]
基本上没有办法用，只有很少量的视频可以播放。

**Comment by coslyk** [comment]
请提供下你播放的视频的地址，谢谢！

**Comment by yinflying** [comment]
采用搜索的方案出来的还是可以播放的，但是其的均会出现网络错误，终端无错误输出！系统ubuntu14.04x64，现在还是使用you-get直接下载观看视频 。

**Comment by coslyk** [comment]
试试直接拖链接到MoonPlayer窗口能播放吗？感觉是firefox扩展的问题。。。
