### ISSUE TITLE
Linux mint18.1下使用出现问题，无法启动（这样描述礼貌些～）。

### ISSUE THREAD

**Issue by i0Ek3** [coslyk/moonplayer#36]
安装什么的都正常，就是无法启动。

**Comment by coslyk** [comment]
@i0Ek3 发下终端下的输出看看？

**Comment by uneed** [comment]
正常使用的

**Comment by i0Ek3** [comment]
ac2064t@ac2064t ~ $ moonplayer
Initialize settings...
Initialize API for Python...
Initialize language support...
Initialize player...
Initialize mpv backend...
Initialize playlist...
Initialize webview...
Initialize ResLibrary...
AttributeError: 'module' object has no attribute 'load_item'
是缺少东西吗？

**Comment by coslyk** [comment]
@i0Ek3 删掉~/.moonplayer/plugins下的文件重启试试

**Comment by i0Ek3** [comment]
删掉那些插件后的确可以启动了，但是没有了插件的资源话该咋整？

**Comment by i0Ek3** [comment]
@uneed 你的插件都使用正常吗？

**Comment by coslyk** [comment]
@i0Ek3 你用的是哪个插件？

**Comment by i0Ek3** [comment]
之前用的是56，爱奇艺的插件，不好使～加载了你编写的这两个插件，搜狐和bilibili，可以正常使用，但播放器上就只显示优酷和搜狐的源，没有bilibili～

**Comment by coslyk** [comment]
@i0Ek3 无法重现你的问题。你有给插件改文件名吗？文件名一定要 res_ 开头才能被识别

**Comment by i0Ek3** [comment]
ofn，命名如你所说～ res_bilibili.py，事实上，插件文件夹里没有生成 res_bilibili.pyc文件，而有res_sohu_tv.pyc文件～

**Comment by i0Ek3** [comment]
不过还是很感谢你的“售后服务”，我想应该是我的一些操作问题，我重新命名原文件名和复制脚本内容后正常使用了～Merci！
