### ISSUE TITLE
亲，搞个高富帅的GUI吧。

### ISSUE THREAD

**Issue by uneed** [coslyk/moonplayer#37]
RT，程序实用，但GUI太差，谈不上用户体验。不如照个现成的。
![screenshot_2017-02-20_19-59-27](https://cloud.githubusercontent.com/assets/4002250/23124543/9a066698-f7a8-11e6-81b4-b0c61473cd9c.png)

**Comment by uneed** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/4002250/23124711/596c559c-f7a9-11e6-80f5-9523cd9171a3.png)

这里很不方便，读取列表，但没略缩图也没文件信息（时间，清晰度等），自然也不能按那些信息排序。要找到所需的内容还要点进去看，很麻烦

**Comment by coslyk** [comment]
@uneed 这个搜索功能我打算以后合并到左边的影视资源里面，现在的话你可以在网页上搜视频然后配合浏览器扩展来使用吧。

**Comment by lowy** [comment]
bililocal那个ui就很漂亮且实用 可惜只支持本地
