### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by MingHuiLiu** [coslyk/moonplayer#38]
In file included from ../src/player.cpp:4:0:
../src/playlist.h: In constructor 'Player::Player(QWidget*)':
../src/playlist.h:35:10: error: 'void Playlist::fileSelected(const QString&, const QString&)' is protected
     void fileSelected(const QString &file, const QString &danmaku);
          ^
../src/player.cpp:144:34: error: within this context
     connect(playlist, &Playlist::fileSelected, player_core, &PlayerCore::openFile);
                                  ^
../src/player.cpp:144:82: error: no matching function for call to 'Player::connect(Playlist*&, void (Playlist::*)(const QString&, const QString&), PlayerCore*&, void (PlayerCore::*)(const QString&, const QString&))'
     connect(playlist, &Playlist::fileSelected, player_core, &PlayerCore::openFile);
                                                                                  ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/QWidget:1,
                 from ../src/player.h:4,
                 from ../src/player.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (Playlist::*)(const QString&, const QString&)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (Playlist::*)(const QString&, const QString&)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (Playlist::*)(const QString&, const QString&)' to 'const char*'
Makefile:433: recipe for target 'player.o' failed
make: *** [player.o] Error 1
02:55:58: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project moonplayer (kit: 桌面)
When executing step "Make"

**Comment by coslyk** [comment]
@MingHuiLiu 请用Qt5编译。
