### ISSUE TITLE
更新mesa后，intel vaapi硬解“黑屏”

### ISSUE THREAD

**Issue by MingHuiLiu** [coslyk/moonplayer#39]
[demux] Not seekable, but enabling seeking on user request.
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
[vo/vaapi] vaPutSurface(): the requested function is not implemented

mesa版本为 Mesa 17.1.0-devel

**Comment by coslyk** [comment]
@MingHuiLiu 这个是驱动的问题了，和播放器没有关系:(

**Comment by coslyk** [comment]
@MingHuiLiu 终端下运行vainfo看看输出正不正常

**Comment by MingHuiLiu** [comment]
没问题，使用vaapi，播放视频时，有声音，黑屏，（终端启动）终端一直输出[vo/vaapi] vaPutSurface(): the requested function is not implemented
vainfo输出如下：
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva 1.8.0.pre1)
vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 1.8.1.pre1 (1.8.1.pre1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointVLD

**Comment by MingHuiLiu** [comment]
@coslyk
