### ISSUE TITLE
moonplayer视频播放优酷不定时闪屏

### ISSUE THREAD

**Issue by bodo005** [coslyk/moonplayer#43]
系统环境是ubuntu mate 16.04.2，不知道是什么原因，视频输出xv和opengl都会闪两三下，然后没事了。硬件是amd fx8350+hd7770，自带开源驱动。

**Comment by coslyk** [comment]
应当和驱动有关。

**Comment by bodo005** [comment]
现在又装了AMD官方闭源amdgpu-pro驱动，一样还是有这个问题

**Comment by coslyk** [comment]
贴下终端输出看看？还有，这是只是播优酷时的问题，还是播其他网站或者本地视频时也有同样的问题？

**Comment by YangtseSu** [comment]
那是在切片，一个视频源是很多小视频。

**Comment by wnpllrzodiac** [comment]
优酷大概3分钟一个切片。闪的频率是这个么
