### ISSUE TITLE
客户端无权播放,201

### ISSUE THREAD

**Issue by jingle0927** [coslyk/moonplayer#44]
![181512xo9j00b6o6ovfx87](https://user-images.githubusercontent.com/26103116/27062273-84ecea3a-501c-11e7-8154-3a7cb9507cb2.png)

**Comment by coslyk** [comment]
Sorry...最近没什么时间维护
这个是you-get解析程序的问题，you-get作者太久没更新了也没办法 :(
打算这几天我手动给you-get打patch，然后发布到ppa上去

**Comment by coslyk** [comment]
@jingle0927 更新好了，你测试下？

**Comment by rekols** [comment]
这速度不错。

**Comment by jingle0927** [comment]
抱歉，一直没有注意，深度商店准备更新到最新版本的，最近下架处理了

**Comment by coslyk** [comment]
@jingle0927 谢谢推广～
