### ISSUE TITLE
git log 是 “New you-get upgrader on macOS”

### ISSUE THREAD

**Issue by jingle0927** [coslyk/moonplayer#45]
![snapshot](https://user-images.githubusercontent.com/26103116/27670033-ca2058e2-5cbc-11e7-920f-92677efe3789.png)

不知道linux是不是不行 我在deepin下

**Comment by coslyk** [comment]
你提供下具体的视频地址吧，不然我也没法诊断。。。我这里是没问题的

另，你的you-get有更新到ppa里面的最新版本嘛？

**Comment by jingle0927** [comment]
更新到了1.5
