### ISSUE TITLE
parse failed

### ISSUE THREAD

**Issue by levinit** [coslyk/moonplayer#47]
![2017-07-27 21-31-46](https://user-images.githubusercontent.com/24387319/28672769-3df0faf8-7313-11e7-9cd9-163035e3dc41.png)
就这个情况。所有频道均如此。
不过最近用you-get -p mpv [url]方式播放bilibili也不行，前几天放优酷也不行，昨天you-get 更新了又好了，bilibili用you-get -p mpv还是不行。

**Comment by coslyk** [comment]
现在B站防抓包了，要检查User Agent和Referrer，不匹配的话服务器会直接拒绝请求，所以直接调用mpv播肯定是不行的
patch我已经写好了，明天发新版本修复这个问题
