### ISSUE TITLE
Network Error:0

### ISSUE THREAD

**Issue by MingHuiLiu** [coslyk/moonplayer#48]
Network Error:0
Connect refused
操作系统Ubuntu16.04
播放器及you-get都是最新

**Comment by coslyk** [comment]
你提供下运行截图，终端下的输出和播放哪个视频，不然我没法诊断

**Comment by MingHuiLiu** [comment]
![2017-08-08 18-06-52](https://user-images.githubusercontent.com/12046018/29067515-83389dfe-7c65-11e7-81bd-1fa710acdb8f.png)
点击视频分类及使用在线视频搜索等都会弹出此错误

**Comment by MingHuiLiu** [comment]
@coslyk

**Comment by coslyk** [comment]
无法复现你的问题。估计和网络环境有关。
贴下终端输出看看？

**Comment by MingHuiLiu** [comment]
问题已解决，个人原因导致的，可能是我之前不小心设置或更改了代理及缓冲大小导致的，具体原因没看，清理文件时顺便把moonplayer的配置文件删了结果就好了
