### ISSUE TITLE
客户端无权播放

### ISSUE THREAD

**Issue by jingle0927** [coslyk/moonplayer#51]
大神，我看1.1.5 最新的发布了打包测试了下 deepin下不行啊，这样上架不了啊。5555

ubuntu下面也有问题。
![virtualbox_ubuntu_04_09_2017_10_32_49](https://user-images.githubusercontent.com/26103116/30010377-dd847bbe-9161-11e7-93c8-7485d76f93f4.png)

**Comment by levinit** [comment]
youku?我这也是

**Comment by coslyk** [comment]
你点Upgrade Parser试试？
MoonPlayer调用了you-get作后台解析，播放不了是you-get的问题，取you-get的github页面反馈吧。

**Comment by levinit** [comment]
你的源里面的you-get还是不够新，去https://github.com/soimort/you-get下载最新的安装，就可以了。
（附：arch用户安装更新的you-get-git 取代community源中的you-get即可）

**Comment by coslyk** [comment]
@jingle0927 @levinit 我知道问题所在了

新版的MoonPlayer已经使用内建的you-get了，不再使用deb的you-get
如果deb的you-get没卸载掉的话，会覆盖内建you-get的设置，导致MoonPlayer调用旧版you-get
把deb的you-get卸载掉就好了

**Comment by coslyk** [comment]
准备写个patch解决覆盖的问题

**Comment by levinit** [comment]
@coslyk  也就是卸载掉you-get就行了？

**Comment by coslyk** [comment]
@levinit 对的，你试试

**Comment by levinit** [comment]
@coslyk 我从aur安装的，卸载了you-get还是不行，安装github最新的you-get就可以了。我去给他反馈一下。

**Comment by coslyk** [comment]
Patch:
https://raw.githubusercontent.com/coslyk/moonplayer/7c8149e862b93c9235c1809422861736871ee203/src/you_get_patched.py
下载这个文件，替换掉/usr/share/moonplayer/you_get_patched.py试试，看看还有没有覆盖问题

**Comment by levinit** [comment]
@coslyk 我安装回有解析问题的老版本you-get，覆盖了你给的py文件，依然还是parse error，换回最新版you-get就行了。因此看来，内建的you-get还是没有优先。

**Comment by coslyk** [comment]
还是无权播放的提示吗？

**Comment by levinit** [comment]
@coslyk 是解析错误

**Comment by coslyk** [comment]
贴出错提示看看

**Comment by levinit** [comment]
测试为优酷亮剑（老版本）第一集

- 只安装moonplayer没安装you-get的，提示
```
Parse failed!
URL:http://v.youku.com/v_show/id_XMTAyMDIyNzY4.html
Traceback (most recent call last):
  File "/usr/share/moonplayer/you_get_patched.py", line 16, in <module>
    import you_get
ModuleNotFoundError: No module named 'you_get'
```

关掉播放器，然后替换了你给的py文件还是提示如上。
点击更新you-get没反应，重开测试依然提示如上。

- 安装moonplayer + you-get，提示
```
Parse failed!
URL:http://v.youku.com/v_show/id_XMTAyMDIyNzY4.html
you-get: 客户端无权播放,201
```

---通过包管理器查看版本
moonplayer是 **1.1.5.r204-1** 
you-get-git是 **0.4.803.20170902.1732-1**

**Comment by coslyk** [comment]
python3 -c "import os; print('%s/.moonplayer/you-get/src/' % os.getenv('HOME'))"
ls ~/.moonplayer
终端执行这两个命令，结果是什么？

**Comment by levinit** [comment]
python3 -c "import os; print('%s/.moonplayer/you-get/src/' % os.getenv('HOME'))"
/home/levin/.moonplayer/you-get/src/
```shell
/home/levin/.moonplayer/you-get/src/
```
ls ~/.moonplayer
```shell
plugins  skins
```
![2017-09-05 14-04-43](https://user-images.githubusercontent.com/24387319/30047333-3aea1c6e-9243-11e7-9609-d4893e0e5f12.png)

**Comment by coslyk** [comment]
从那两个命令输出结果来看，你没有点那个“更新解析程序”。。。点了就有内建you-get了

难道说aur里面没把内建you-get的更新程序打包进去？我没有arch测试不了，至少我这里debian是没有问题的

**Comment by coslyk** [comment]
播放器右键点 更新you-get，之后应当能看到~/.moonplayer/you-get这个文件夹，这个就是内建you-get

**Comment by levinit** [comment]
@coslyk 点了的，点了也没有下载，还是空空如也的。在/usr/share/moonplayer下面有这个文件的。
aur打包是把你的代码下载下来，然后执行make这些，把生成的包安装到指定位置，你这包里面有的都会有的。

**Comment by levinit** [comment]
点击更新you-get是不是执行了你代码文件夹src中的upgrade-you-get.sh这个脚本？这个脚本在/usr/share/moonplayer/里面是有的。

我看了下这个sh代码，# Download latest version里面有一句`$DOWNLOADER you-get.zip "https://github.com/soimort/you-get/archive/develop.zip"，这个$DOWNLOADER变量值"wget -q -O"，也就是说在下载是会执行
```shell
wget -q -O you-get.zip https://github.com/soimort/you-get/archive/develop.zip
```
对吗？可能是我没安装wget的缘故(arch不带wget，我也没用wget，现在才发现）……建议这里也用curl取代wget（我看上面mac就是用的curl下载）

另外，我发现这个sh文件没有带可执行权限……所以我点了升级没反应？会不会也有这个原因

**Comment by levinit** [comment]
@coslyk 我单独执行了一下这个upgrade-you-get.sh文件，报了一句错误，就是第51行
```python
python -c "import sys, json; print json.load(sys.stdin)['commit']['sha']"
```
你这里print用的py2的写法，arch默认的是py3，我加上了括号，
```python
python -c "import sys, json; print(json.load(sys.stdin)['commit']['sha'])"
```
再单独执行这个文件，you-get下载成功，可能这就是bug所在?

**Comment by coslyk** [comment]
@levinit 终于找到问题所在了，非常感谢你辛勤的调试^_^

**Comment by levinit** [comment]
libqtermwidget这个包在有的发行版可能会叫做`qtermwidget`（例如arch及其衍生版、slackware、centos及其衍生版。https://pkgs.org/download/qtermwidget。请教我雷锋。

**Comment by jingle0927** [comment]
@coslyk  那我重新拉1.1.7打包试试。

**Comment by coslyk** [comment]
辛苦啦，谢谢两位～

**Comment by ls929931823** [comment]
大神，膜拜大神，又出现以前的那种“客户端无权播放了。2018-01-09还是好好的，到10日就不行了。更新了解析程序也不行。优酷网页做调整了？
提示：Parse failed!
URL:http://v.youku.com/v_show/id_XMzA1NzU5MDY0OA==.html"></a><i class="bg"></i><img class="" src="http://r1.ykimg.com/051600005959B76FADBA1FA70B07C42D" alt="神偷奶爸3" /></div><ul class="info-list"><li class="title"><a title=
you-get: 客户端无权播放,201

**Comment by coslyk** [comment]
@ls929931823 you-get太久没更了，我也没办法
打算把后端从you-get换成ykdl了
