### ISSUE TITLE
弹幕怎么关

### ISSUE THREAD

**Issue by levinit** [coslyk/moonplayer#52]
没看到选项。可能我的需求有点不同哈哈。。。我想关弹幕。

**Comment by levinit** [comment]
另外提两个后续改进建议：
- 搜索历史记录保存
- 添加收藏（？这个不会做的话就不建议了）

**Comment by coslyk** [comment]
右键-字幕-可见，或者直接按快捷键D

**Comment by coslyk** [comment]
建议不错，不过最近应该没时间弄了
