### ISSUE TITLE
影片名字只能显示一行，如果太长就看不到后面的文字

### ISSUE THREAD

**Issue by levinit** [coslyk/moonplayer#53]
- 建议：不要限制名字显示的行数，一些视频好好多部，名字一长 完全看不到后面写的什么。比如搜索“海绵宝宝”，显示出来的名字都是“海绵宝宝...”，完全不知道谁是第一部。可以考虑的解决方案：
增加列表显示
鼠标放置到名字上显示全名
不限制名称显示行数（或者至少可以显示2行，对大多数名称应该足够了）
![2017-09-11 14-39-54](https://user-images.githubusercontent.com/24387319/30261432-27bf9266-96ff-11e7-9615-098f6b7b2c66.png)

#52 的建议：
- 增加搜索历史记录
- 如果可以增加收藏功能

**Comment by coslyk** [comment]
谢谢建议，最新的commit已经加上啦～
