### ISSUE TITLE
chrome扩展用不了！

### ISSUE THREAD

**Issue by feiyingchen** [coslyk/moonplayer#59]
deepin下最新版本的chrome浏览器扩展程序无法使用，提示：此扩展程序可能已损坏。重新下载的也不行！

**Comment by coslyk** [comment]
我这正常。。。
你有执行压缩包里的那个脚本吗？

**Comment by feiyingchen** [comment]
有的！

**Comment by feiyingchen** [comment]
已经找到了原因，在最近两个chrome版本中moonplayer插件与switchyomega插件冲突所致，删除switchyomega插件后就可以了。

**Comment by coslyk** [comment]
最新版已在Chrome商店上架，关闭issue。
