### ISSUE TITLE
Offer guix, snap or flatpak for easy cross-platform installation

### ISSUE THREAD

**Issue by baimafeima** [coslyk/moonplayer#60]
Would you consider making a snap package available for easy cross-platform installation? There are lots of snaps already available here: https://snapcraft.io/store/

**Comment by dkgdsc** [comment]
你们还保持snap版的更新吗？！

**Comment by coslyk** [comment]
@dkgdsc snap不是我维护的。。我没精力维护那么多~_~

**Comment by dkgdsc** [comment]
snap版不是最新版吧？！不然我一打开snap版moonplyer，说有更新，用snap的更新更新下，说所有的snap应用都是最新版

**Comment by coslyk** [comment]
建议直接使用ppa源更新

**Comment by baimafeima** [comment]
What about Flatpaks? I cannot install your program because it is only offered as a tarball.

**Comment by coslyk** [comment]
@baimafeima Sorry but I am not able to maintain so many packages. Consider using Apt or AUR instead. Check [Download](https://github.com/coslyk/moonplayer/wiki/DownloadZH) for details.

**Comment by baimafeima** [comment]
@coslyk Unfortunately, I'm neither using Debian nor Arch. It would be great to have it available at least as one "universal package", `guix`, `snap` or `flatpak`.

**Comment by coslyk** [comment]
Close issue because Flatpak is available now.
