### ISSUE TITLE
18.04无法显示

### ISSUE THREAD

**Issue by wangling12** [coslyk/moonplayer#64]
Ubuntu 18.04 打开效果如下
![2018-05-31 12-34-05](https://user-images.githubusercontent.com/24770600/40761636-ff93868c-64ce-11e8-9567-904bf96eda05.png)
用右键菜单打开文件后也是只有声音没有画面。
终端输出如下：

> Initialize settings...
Initialize API for Python...
Initialize language support...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Initialize mpv backend...
Initialize playlist...
Initialize ResLibrary...
Initialize downloader...
OpenGL Version: 4.6
[cplayer] Warning: option --hwdec-preload was replaced with --opengl-hwdec-interop and might be removed in the future.

**Comment by coslyk** [comment]
无法复现你的问题。。。T_T

**Comment by akkuman** [comment]
manjaro kde也是这样

**Comment by coslyk** [comment]
@wangling12 @akkuman 显卡是什么呢？视频打开后有别的错误输出吗？

**Comment by akkuman** [comment]
显卡是gtx950  ，打开后就是黑屏
![Screenshot_20180726_164551.png](https://i.loli.net/2018/07/26/5b598a6783c5e.png)

**Comment by coslyk** [comment]
@akkuman 试试AppImage版本：http://pan.baidu.com/s/1gptym

**Comment by wangling12** [comment]
@coslyk 
显卡860m:
![2018-07-27 09-30-44](https://user-images.githubusercontent.com/24770600/43296898-bc0e0aa2-9180-11e8-8e89-95c56ba6e028.png)
AppImage版本结果：

> ./MoonPlayer-x86_64.AppImage 
Initialize settings...
Initialize API for Python...
Initialize language support...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Initialize mpv backend...
Initialize playlist...
Initialize ResLibrary...
Initialize downloader...
OpenGL Version: 4.6
[cplayer] Warning: option --hwdec-preload was replaced with --opengl-hwdec-interop and might be removed in the future.

和安装后运行效果一样。

另外我注意到昨天ubuntu版更新了一个版本，然而效果依旧同上

**Comment by coslyk** [comment]
貌似出问题的都是N卡。。。我没有硬件没法测试-_-
把设置里的硬件解码改成vdpau试试？
@wangling12 @akkuman

**Comment by wangling12** [comment]
@coslyk 
改完之后正常了，另外能不能把顺手把那个Warning改了，强迫症感觉挺别扭的hhh

**Comment by coslyk** [comment]
@wangling12 好的，多谢测试，知道问题在哪了hhh
你指的是哪个warning？
