### ISSUE TITLE
AppImage doesn't work

### ISSUE THREAD

**Issue by baimafeima** [coslyk/moonplayer#69]
I downloaded the latest AppImage file but it doesn't run after I made it executable. Can someone else test whether it's because of the AppImage or my system?

**Comment by baimafeima** [comment]
How could I launch an AppImage from the terminal to check its output?

**Comment by coslyk** [comment]
@baimafeima Run ./xxx.AppImage just like other executable files

**Comment by baimafeima** [comment]
Then I get the error report: `bash: Run: command not found...`

**Comment by coslyk** [comment]
@baimafeima Oh my God you should type "./MoonPlayer-x86_64.AppImage" in the terminal...

**Comment by baimafeima** [comment]
Thanks, then I get this error message: 
`./MoonPlayer-x86_64.AppImage: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory`

**Comment by coslyk** [comment]
Can you try installing libjack on your system?

**Comment by coslyk** [comment]
I have repacked it and uploaded to the release page. Try downloading `Moon_Player-1.9.2.glibc2.17-x86_64.AppImage` ?

**Comment by baimafeima** [comment]
The latest `Moon_Player-1.9.2.glibc2.17-x86_64.AppImage` unfortunately doesn't work either. Memory is suddenly up to 2.45 GiB when I usually only need around 700. `Libjack` is not in the repository of my operating system, so I have no way of installing it.

**Comment by coslyk** [comment]
Can you tell me which Linux distribution you are using?

**Comment by baimafeima** [comment]
I'm using [Solus](https://getsol.us/home/).

**Comment by coslyk** [comment]
As I googled, the package `jack-audio-connection-kit` on Solus contains libjack. Try installing it?
If this doesn't work, try installing mpv, then all dependencies should be sufficient.

**Comment by coslyk** [comment]
Please install all the missing libraries according to the terminal output until all the dependencies are sufficient. You can use Google to find out the name of packages which contain the libraries.

**Comment by baimafeima** [comment]
I cannot find these libraries in my operating system. Installing them separately could potentially break my system. I thought they should all be bundled in the AppImage itself?

**Comment by coslyk** [comment]
The AppImage is bundled automatically by linuxdeploy-qt, so it should be the bug of this tool that it can't bundle all the dependencies correctly.
In this case you'd better to compile it by yourself.

**Comment by baimafeima** [comment]
@probonopd Would you have an idea how this can be solved? Does the AppImage bundled through linuxdeploy-qt work on your machine? Many thanks in advance.

**Comment by coslyk** [comment]
After all I think you'd better compile it yourself, because as video player its performance is strongly depends on the drivers on your system, and it's not guaranteed that the libraries bundled in AppImage are compatible with the drivers.

**Comment by probonopd** [comment]
> @probonopd Would you have an idea how this can be solved? 

The AppImage needs to bundle any library that cannot be expected to be there on each target system by default.

> Does the AppImage bundled through linuxdeploy-qt work on your machine?

You can watch the test log at https://github.com/AppImage/appimage.github.io/pull/870

**Comment by coslyk** [comment]
After reading the source code I found that some libraries are automatically excluded by the AppImage building tools, because most of the Linux distributions include them and they need to be compatible with your platform, e.g. driver files. Bundling them into AppImage may cause the program not work.
There is a list of them: https://github.com/AppImage/AppImages/blob/master/excludelist
So if these libraries are not installed in your system, you should install them yourself.

**Comment by probonopd** [comment]
> So if these libraries are not installed in your system, you should install them yourself.

These libraries are on the list _because_ they are assumed to be part of every system. On which kind of system are they missing?

**Comment by baimafeima** [comment]
@probonopd I'm on [Solus](https://getsol.us/home/).

**Comment by probonopd** [comment]
Maybe you can suggest in their bug tracker to install the libraries listed on https://github.com/AppImage/AppImages/blob/master/excludelist by default in order to maximize out-of-the-box compatibility with many AppImages. Thanks.

**Comment by coslyk** [comment]
I just repacked the AppImage to include libkeyutils.

**Comment by baimafeima** [comment]
@probonopd My account on their development tracker was suspended as they don't like my political position on anti-censorship and freedom. It's a pity that they don't get politics right but after all they are a technically fascinating Linux distribution. So unfortunately, I cannot help with that but it would be great if you could do that as you are the main developer. 
@coslyk Thanks for your continued efforts to help getting Moonplayer to work on Solus. Where can I download the latest AppImage to test it?

**Comment by coslyk** [comment]
I don't understand what you mean by saying "political position". I believe that no one will refuse your feedback just because of this.Maybe because they think that this software may lead to copyright problems. As a tool MoonPlayer can't inspect whether the video is copyright,  users should inspect it themselves. You can explain to them that MoonPlayer is something just like youtube-dl.The repacked AppImage is available on the Download page.

**Comment by baimafeima** [comment]
@coslyk Yes, exactly. This is what I explained and in addition to that it allows users to not be tracked by nasty cookies. At least I hope so. Unfortunately, my comment was deleted and shortly thereafter my account frozen. Maybe that had a bad day.

**Comment by probonopd** [comment]
Is there a working AppImage now?

**Comment by coslyk** [comment]
@probonopd You can try this: https://github.com/coslyk/AppImageCollection/releases/download/init/MoonPlayer-2.7-x86_64.AppImage

But the `libva` is not backward compatible, the hardware decoding may not work, so I don't recommend to use the AppImage version here (T_T)

**Comment by probonopd** [comment]
Thank you. It does launch now.

**Comment by coslyk** [comment]
@probonopd Thank you for your test!

The packaged `libva1` from Ubuntu xenial doesn't work on my host system, which use `libva2` by default. It seems that they use different APIs. Do you have any idea to solve it?

![va](https://user-images.githubusercontent.com/6695223/57951582-be2fe100-78ea-11e9-9b11-0c68b128b956.png)

**Comment by probonopd** [comment]
Are you running Wayland? (Just guessing here, I have no real clue about VO)

**Comment by coslyk** [comment]
@probonopd I'm using XWindow.

**Comment by probonopd** [comment]
Sorry I do not know then.

**Comment by coslyk** [comment]
Maybe this is a solution: https://voltaicforge.com/linux/steam-vaapi-fix-linux/#

We can make it prefer to use the host system's `libva`, if the host system does'nt have it then use the packaged one.

**Comment by probonopd** [comment]
Sounds good, worth trying.
