### ISSUE TITLE
优酷的视频似乎都放不了。。。

### ISSUE THREAD

**Issue by jay763190097** [coslyk/moonplayer#70]
![_ _20181024001627](https://user-images.githubusercontent.com/16317178/47375148-2dad6b80-d722-11e8-8abe-9db7572f9a3c.png)
![_ _20181024001637](https://user-images.githubusercontent.com/16317178/47375149-2e460200-d722-11e8-9bf9-05ef9e3010c5.png)

**Comment by coslyk** [comment]
终端下直接输python会有问题吗？
看起来似乎是python环境的问题，可以看看这个：https://blog.csdn.net/learning_oracle_lh/article/details/50484298

**Comment by jay763190097** [comment]
```
jay@jay-PC:~$ python -V
Python 2.7.15
jay@jay-PC:~$ python
Python 2.7.15 (default, May  1 2018, 05:55:50) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
jay@jay-PC:~$ pyenv versions
* system (set by /home/jay/.pyenv/version)
jay@jay-PC:~$ echo $LANG $LANGUAGE
zh_CN.UTF-8 zh_CN.UTF-8
jay@jay-PC:~$ echo $PYTHONHOME

jay@jay-PC:~$ echo $PYTHONPATH
/usr/local/lib/python2.7/

jay@jay-PC:/usr/bin$ find python*
python
python2
python2.7
python3
python3.6
python3.6m
python3m

```

唉，不知道怎么解决

**Comment by jay763190097** [comment]
![_ _20181027123325](https://user-images.githubusercontent.com/16317178/47599620-8a3fad80-d9e4-11e8-87e3-441f455ecb7e.png)
/usr/bin下移除python3后出现这个
依赖python3?

**Comment by coslyk** [comment]
你要不用AppImage试试吧 -_-
https://github.com/coslyk/moonplayer/releases

**Comment by jay763190097** [comment]
突然发现，我就是用的appimage应该和我本地的python环境没关系吧

**Comment by coslyk** [comment]
那就试试其他的安装方法吧，AppImage好像问题还挺多的。。。
https://github.com/coslyk/moonplayer/wiki/DownloadZH

**Comment by coslyk** [comment]
重新打包了下AppImage，把完整的python打包进去了，试试这个？
http://pan.baidu.com/s/1gptym

**Comment by jay763190097** [comment]
还是有些视频播放不了
![image](https://user-images.githubusercontent.com/16317178/48234720-ba7c4880-e3f5-11e8-8507-fa61eff23dbc.png)
之前是点更新解析程序有报python的错误，现在点更新解析程序没问题了
![image](https://user-images.githubusercontent.com/16317178/48234784-05965b80-e3f6-11e8-8a26-df8730c5047d.png)
但有些是更新也没用。

然后点show Details 里面还是那个python的错误
![image](https://user-images.githubusercontent.com/16317178/48234735-d253cc80-e3f5-11e8-8c27-2b68df39f5a8.png)

**Comment by coslyk** [comment]
是仅仅you-get有Python的问题还是两种解析都有问题？

**Comment by jay763190097** [comment]
只有you-get有。
第一次解析失败应该是因为客户端无权播放
```
WARNING:downloader:failed to import ThreadPoolExecutor!
WARNING:downloader:multithread download disabled!
WARNING:downloader:please install concurrent.futures from https://github.com/agronholm/pythonfutures !
CRITICAL:YKDL:客户端无权播放,201
```
尝试you-get就会有python的问题

**Comment by coslyk** [comment]
ykdl的问题就去ykdl项目的issue那里反馈下you-get的问题我再研究研究😂

**Comment by coslyk** [comment]
懒得折腾AppImage了，问题还是好多，还是决定用Flatpak打包好了，省事，可靠性高点

**Comment by coslyk** [comment]
@jay763190097 试试最新的：
http://pan.baidu.com/s/1gptym
https://github.com/coslyk/moonplayer/releases

**Comment by jay763190097** [comment]
```
Traceback (most recent call last):
  File "/tmp/.mount_MoonPlM5D2nq/usr/share/moonplayer/you_get_patched.py", line 16, in <module>
    import you_get
ModuleNotFoundError: No module named 'you_get'
```
![image](https://user-images.githubusercontent.com/16317178/48417634-311a9c80-e78e-11e8-9271-20679b103161.png)

**Comment by jay763190097** [comment]
![image](https://user-images.githubusercontent.com/16317178/48418102-6a074100-e78f-11e8-9f8d-0a4104de2a50.png)

```
WARNING:downloader:failed to import ThreadPoolExecutor!
WARNING:downloader:multithread download disabled!
WARNING:downloader:please install concurrent.futures from https://github.com/agronholm/pythonfutures !

```

警告内容

**Comment by coslyk** [comment]
这个warning不影响，ykdl只用作解析，不需要用到里面的downloader

**Comment by jay763190097** [comment]
第一次打开不管是appimage还是flatpak都有一个错误。
![_ _20181119224118](https://user-images.githubusercontent.com/16317178/48714940-c7e3cf00-ec4e-11e8-91e0-3ddcc295dcf1.png)

然后今天发现，每个视频都是最长才6分33秒，这个是什么原因呢？
![_ _20181119230135](https://user-images.githubusercontent.com/16317178/48715066-1beeb380-ec4f-11e8-872d-14848897c651.png)

**Comment by coslyk** [comment]
因为优酷会把视频切成最长6:33的片段

**Comment by coslyk** [comment]
这个错误提示更新一下解析程序就好了

**Comment by jay763190097** [comment]
是的，那个更新一下就没了。
![_ _20181120000440](https://user-images.githubusercontent.com/16317178/48719234-f4501900-ec57-11e8-8440-5786a93d7fc2.png)
似乎没有一个完整的电影。。。。，一个电影差不多两个小时

**Comment by coslyk** [comment]
打算写一个暴力解析器了。。。直接内建浏览器后台打开视频网页，监视网络通讯，捕获到视频地址就关闭浏览器然后输出视频地址，这样视频网站怎么变算法都可以解析了，方法简单粗暴 *_*

**Comment by jay763190097** [comment]
厉害，node.js有PhantomJS  Puppeteer

**Comment by jay763190097** [comment]
v2.3已经可以播放完整视频的，界面上优化点，体验上优化点就完美的客户端了。

**Comment by coslyk** [comment]
> 
> 
> 厉害，node.js有PhantomJS Puppeteer

毕竟我也是业余的，懒得研究其他Toolkit了，直接用QtWebkit，可以和Qt的网络模块集成，抓数据挺方便的。而且貌似PhantomJS也是基于QtWebkit的。。。

**Comment by coslyk** [comment]
> 
> 
> v2.3已经可以播放完整视频的，界面上优化点，体验上优化点就完美的客户端了。

你觉得还有啥改进的点呢？

**Comment by jay763190097** [comment]
比如把查询内容页面固定到播放窗口右边做一个边栏显示隐藏，这样的话可以在看视频的时候，搜索其他内容。或者选择下一集播放

**Comment by jay763190097** [comment]
有时间我试试，哈哈
