### ISSUE TITLE
Archlinux不能编译，pyapi.cpp找不到yougetbridge.h

### ISSUE THREAD

**Issue by heavysink** [coslyk/moonplayer#71]
qmake-qt5
make
pyapi.cpp:17:10: fatal error: yougetbridge.h: No such file or directory
 #include "yougetbridge.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:909: pyapi.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by coslyk** [comment]
已修复，谢谢反馈～ @heavysink 
如果可以的话archCN源的配置里加上`use_latest_release: true`吧，最新的commit不一定能正常解析视频的 不适合推给用户，谢啦～
