### ISSUE TITLE
不能观看除了搜狐以外的在线视频

### ISSUE THREAD

**Issue by weilexuexi** [coslyk/moonplayer#77]
在线视频里面只能看搜狐的视频，点另外几个插件都会出现这个问题NETWORK ERROR :0  TLS INNITIALIZATION FAILED

![无标题](https://user-images.githubusercontent.com/33811049/54876045-48584d80-4e44-11e9-8b23-b1f44b69b914.png)

**Comment by coslyk** [comment]
应该是缺了运行库
https://www.microsoft.com/en-us/download/details.aspx?id=40784
下载x86版本的安装下试试

**Comment by weilexuexi** [comment]
@coslyk 感谢作者的回复，这个问题已经解决了，非常nice的软件，新装的电脑就是没有运行库，装上就可以了。现在又有个新的问题，就是我现在用chrome浏览器，然后插件我装上了，但是在视频网站右键open with moonplayer的时候却没有反应，是不是Windows版本的没有安装不能调用啊？我的moonplayer是解压在桌面的。

**Comment by coslyk** [comment]
@weilexuexi win版也是最近才做出来的，还不完善，暂时还不能用浏览器扩展，抱歉哈

**Comment by weilexuexi** [comment]
@coslyk 噢噢噢，好的好的，谢谢作者，你这个软件太好用啦，除了不能看那些VIp的视频，别的都超级好，加油加油做的更好呀！
