### ISSUE TITLE
建议添加视频下载和画质选择的默认选项

### ISSUE THREAD

**Issue by susices** [coslyk/moonplayer#78]
希望可以在设置里选择 打开一个视频链接后默认是下载或者在线播放，画质默认最高或最低
如果有这个功能配合浏览器插件看视频就很方便了，现在每次都要额外点两次

**Comment by coslyk** [comment]
谢谢建议。下个版本会加上。

**Comment by coslyk** [comment]
已添加此功能，关闭issue。
