### ISSUE TITLE
提供fedora/rhel rpm包

### ISSUE THREAD

**Issue by 1dot75cm** [coslyk/moonplayer#8]
项目地址：https://copr.fedoraproject.org/coprs/mosquito/myrepo/
支持 fedora 19/20/21/rawhide，rhel 7

**Comment by 1dot75cm** [comment]
在Fedora23中，Qt 4.8.6 编译失败，Qt 5.5.1 编译正常。

**Comment by coslyk** [comment]
MoonPlayer已经不支持Qt4了啊，用Qt5就好了
