### ISSUE TITLE
appimage

### ISSUE THREAD

**Issue by Lucas-bash** [coslyk/moonplayer#82]
Can you keep providing this amazing app packed as appimage. thanks a lot for you great work.

**Comment by coslyk** [comment]
The AppImage has problem with the hardware decoding, so I don't provide the AppImage for stable release now. I'm working on it to solve the problem. Once it's solved I will put it into the stable release.
You can test the AppImage of the latest [beta release](https://github.com/coslyk/moonplayer/releases) ^_^

**Comment by ghost** [comment]
Thx. I know how hard it is. Is it work in slackware based ?

Em segunda-feira, 16 de dezembro de 2019, coslyk <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
Try to look after selur on github his codes can be useful for you, or just
google about selur.de where you may find some software that can helps you.

Em segunda-feira, 16 de dezembro de 2019, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:

**Comment by ghost** [comment]
Today I have tested you alfa version and it seems pretty solid, I have done
in four different desktop computers and worked pretty well. Even the old
version you've made worked fine in my computers, the 2.7 and the 2.4
releases are both good for me.
If you have some issue try to apply ffmpeg on it, it maybe can be good for
you in way to seek for compatibility.

Em segunda-feira, 16 de dezembro de 2019, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:

**Comment by coslyk** [comment]
Thanks for your testing!
I've provided the AppImage for the latest release. Enjoy :)

**Comment by ghost** [comment]
thx for you great work. it's perfect. see you soon.

Em sex., 3 de jan. de 2020 às 17:35, coslyk <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
Hi again. How can I push files over 100 mb in my github account ? I have
made an appimage of apache open office latest version how can I push it up
to github ? I am having some warnings.

Em sábado, 8 de fevereiro de 2020, coslyk <notifications@github.com>
escreveu:

**Comment by coslyk** [comment]
What's the error? According to https://help.github.com/en/github/managing-large-files/distributing-large-binaries, you should be able to push files which < 2GB.

**Comment by ghost** [comment]
when it goes over 100 mb it gives to me an error that I can't push the file
over 100 mb. can I send it trough zsync or something related to that?

Em seg., 10 de fev. de 2020 às 12:16, coslyk <notifications@github.com>
escreveu:
