### ISSUE TITLE
希望提供deb包

### ISSUE THREAD

**Issue by feiyingchen** [coslyk/moonplayer#85]
新手不会打包，尝试安装flatpak格式，一直安装不上。之前的版本一直是添加源安装的，记得之前也有deb格式的，现在没有了？希望能提供，或者有在神帮忙打包一个。谢谢了！

**Comment by coslyk** [comment]
为何安装不上，能提供一下详细的安装日志吗？
ppa源我不打算继续维护了，我精力有限维护不过来。Debian用户可以按照 [Wiki页面](https://github.com/coslyk/moonplayer/wiki/DownloadZH) 用apt安装，Ubuntu用户建议使用Flatpak / AppImage.

**Comment by feiyingchen** [comment]
flatpak安装速度太慢了，两个小时还没安装好，还在下载。

**Comment by coslyk** [comment]
可以尝试直接安装Debian的包，Ubuntu 20.04以上理论上可行：https://dl.bintray.com/debianopt/debianopt/pool/main/m/moonplayer/
