### ISSUE TITLE
观看优酷视频时 paser failed error，Process failed to start :系统找不到指定文件

### ISSUE THREAD

**Issue by handsomeprince** [coslyk/moonplayer#87]
![QQ截图20200403164418](https://user-images.githubusercontent.com/17959484/78345135-f9550480-75cf-11ea-8bcc-582005525e72.png)
不知道哪里出问题了，请帮助看看

**Comment by handsomeprince** [comment]
windows 系统 使用VERSION 3.1版本软件

**Comment by handsomeprince** [comment]
![QQ截图20200403164418](https://user-images.githubusercontent.com/17959484/78345700-8e57fd80-75d0-11ea-986d-25da97f1fd1a.png)

**Comment by coslyk** [comment]
点一下“更新解析程序”就可以了
