### ISSUE TITLE
invidio search option

### ISSUE THREAD

**Issue by danrobi11** [coslyk/moonplayer#93]
Hello
First, thank you much for moonplayer :+1: 
Is it possible to add invidio as search option plz, thank you!

**Comment by coslyk** [comment]
Isn't the content of Invidio exactly the same as Youtube? :)

**Comment by smaragdus** [comment]
[Invidious](https://invidio.us/) will be shutting down soon:

> This instance will be shutting down on September 1st.

**screen:**
![Invidious - 2020-08-14 - 002](https://user-images.githubusercontent.com/9025757/90261950-543c1980-de56-11ea-8bab-3a6221fbd4e6.png)

**post:**
[Stepping away from open source](https://omar.yt/posts/stepping-away-from-open-source)
