### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ghost** [coslyk/moonplayer#95]
Hello again? can I make a few questions for you?
lucasmzainote@gmail.com

**Comment by coslyk** [comment]
Please submit issues here directly and clearly.

**Comment by ghost** [comment]
hi. I don't have nothing related to your app.
it's just a few questions.
how do I pack and unpack .elf file static and dynamic linked?
how can I pack and python application as appimage ex. catfsih?
do I need to pack the qt5 folder or just deploy such folder and after
delete, and only leave the qt plugins?
I belive I am packing a lot stuff that is not needed in my aplications.

Em ter., 21 de jul. de 2020 às 13:50, coslyk <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
hi. I don't have nothing related to your app.
it's just a few questions.
how do I pack and unpack .elf file static and dynamic linked?
how can I pack a python application as appimage ex. catfsih?
do I need to pack the qt5 folder or just deploy such folder and after
delete it leaving inside only the qt5 plugins?
I belive I am packing a lot stuff that is not needed in my aplications.

Em qua., 22 de jul. de 2020 às 20:51, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:

**Comment by ghost** [comment]
do you have whatsapp ? if you have send me your phone number for interact
and change some ideas.
thank you!

Em qua., 22 de jul. de 2020 às 21:00, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:

**Comment by coslyk** [comment]
Sorry but here is the place to discuss problems related to this app. I don't have the knowledge covering your questions, too.

For general questions, I suggest you to go to [Stack Overfow](https://stackoverflow.com/questions).
